language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- npm test
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: Egok0OGq4k/bJQDvhXeGm+rHBuDYx24iAO1C7EtjWeKg1roCtP/EI9UyB59wE8XApacLCMhohIWoo2xZmHrqLGZpKOp7ut1Uh3W6Y3vF3qX+IxfcehI9iI3Zq56/K+z7HePg9ruIXn7/QLxy1Z6kenLUBMfd3dQFpCpDZJCNu+ARWnQbWWcT85ylnKy+3nUEzIgAGf+WCj8RqjHxzLQ+JR7WcHoqqrcvdiBwZ/ZCtX9xR0Ofnc+I3ak/R+08J9GyobZuri084LcbVEwfKBxQFdiQuGqUv+v4QdCkWryxH47qWwiMEWDY127Q7JE/M4PmeFpe2WgDwWIbBMOqM55egebB7XMsKbMb8eNidgMCFCKxraSwRtx/a4IjPRNDqNDDHfMCqRFRKgyWp5ZpWNWiTvQhatuPcCtKPE9y7uYgWmWQ/AVcVkOzmwVGPUaMaOJISPvFAsfssrnsew7f0vWZbYs5MSbbc+B4XVhXtcAjSy8YYD5pCXtsZ3ubgXuxqvRUeTQ4JBfJibe/u91p6OSiYoRCr6Yl3hgwt3f49pDwPbf5jycvMPVSzjGcuah/sEOU2NtrJcLbVcXb9ea4AfQGogW3/kGEUT5gicNtrhq/HUEgIS6PCzkSvf3aVWRVHlOYqqc7w98P4fFsfaMCvgvHOWeWGPKRyRSTU8taUH3190g=
  on:
    repo: kuzzleio/kuzzle-sdk-login-oauth-popup
    branch: master